# Generated by Django 5.2.5 on 2025-10-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_alter_perfume_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
