# Generated by Django 5.2.5 on 2025-10-28 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0004_calificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistorialVisualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones', to='perfumes.perfume')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualización',
                'verbose_name_plural': 'Visualizaciones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', '-fecha'], name='perfumes_hi_usuario_8197ad_idx'), models.Index(fields=['session_key', '-fecha'], name='perfumes_hi_session_d4e0e1_idx')],
            },
        ),
    ]
