# Generated by Django 5.2.5 on 2025-10-28 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('notificar_nuevos_perfumes', models.BooleanField(default=True, help_text='Recibir email cuando se agreguen nuevos perfumes', verbose_name='Notificar nuevos perfumes')),
                ('notificar_promociones', models.BooleanField(default=True, help_text='Recibir email sobre descuentos y ofertas', verbose_name='Notificar promociones')),
                ('notificar_newsletter', models.BooleanField(default=False, help_text='Recibir boletín mensual con novedades', verbose_name='Newsletter mensual')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
